baseURL = "https://example.com"
languageCode = "en-us"
title = "Home"
themesDir = "../.."
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"

  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false

  enable_dark_mode = true

  addFrame = true
  addDot = true

  highlightColor = '#7b16ff'